version: '3'
services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/graphql-demo
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
